### ISSUE TITLE
Cannot load module

### ISSUE THREAD

**Issue by maksimse** [dav3860/vmbix_zabbix_module#12]
Hello,
Both agent and server cannot load module.

agent log:
 31642:20190504:135727.249 cannot load module "vmbix.so": /usr/lib/zabbix/modules/vmbix.so: undefined symbol: __zbx_zbx_dsprintf

server log:
 18979:20190504:135054.500 cannot load module "vmbix.so": /usr/lib/zabbix/modules/vmbix.so: undefined symbol: __zbx_zbx_dsprintf

rpm -ihv vmbix-zabbix-module-1.3.34-zabbix-4.0-1.x86_64.rpm
zabbix_server (Zabbix) 4.0.7

Any ideas?

**Comment by maksimse** [comment]
package vmbix-2.8.1.188-1.x86_64 is already installed

**Comment by whosgonna** [comment]
This looks very similar to the issue reported in dav3860/vmbix#56 .  Are you able to manually compile the module again the 4.0.7 codebase?

**Comment by maksimse** [comment]
It says common.h cannot be located if I compile.

**Comment by maksimse** [comment]
[root@zabbix01 vmbix_zabbix_module]# make vmbix-4.0
gcc -shared -o vmbix.so vmbix-4.0.c -I../../../include -fPIC
vmbix-4.0.c:23:20: fatal error: common.h: No such file or directory
 #include "common.h"
                    ^
compilation terminated.
make: *** [vmbix-4.0] Error 1

**Comment by maksimse** [comment]
Installed

Kernel-devel
Kernel-headers

Did not help

**Comment by whosgonna** [comment]
To be sure: you downloaded the Zabbix source code, copied the vmbix module
source code to the appropriate directory, then are trying to compile?

**Comment by maksimse** [comment]
1. tar -xzvpf zabbix-4.0.7.tar.gz zabbix-4.0.7
2. cd zabbix-4.0.7/src/modules/
3. git clone https://github.com/dav3860/vmbix_zabbix_module.git
4. cd vmbix_zabbix_module/
5. [root@zabbix01 vmbix_zabbix_module]# make vmbix-4.0
gcc -shared -o vmbix.so vmbix-4.0.c -I../../../include -fPIC
In file included from ../../../include/common.h:23:0,
                 from vmbix-4.0.c:23:
../../../include/sysinc.h:23:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [vmbix-4.0] Error 1
6. [root@zabbix01 vmbix_zabbix_module]# pwd
/root/zabbix-4.0.7/src/modules/vmbix_zabbix_module

**Comment by whosgonna** [comment]
It looks like you missed the config step. After extracting the Zabbix
source:

cd <source_zabbix>

Then:

./configure --with-openssl --enable-ipv6

Then cd /src/modules, and pickup with your step 3.

**Comment by maksimse** [comment]
You are right. It confused me that the manual says "for Zabbix 3."
Anyway, it is working now. My mistakes were:
1. did not compile against zabbix 4.0.7 source code.
2. missed ./configure part.
Problem solved, thank you.
