### ISSUE TITLE
unknown parameter "serviceurl"

### ISSUE THREAD

**Issue by FireHelmet** [dav3860/vmbix_zabbix_module#2]
Dear dav3860,

I'm trying to use vmbix module on Zabbix 3.0.1, but when I restart the zabbix-server or zabbix-agent I have this error message in log 

zabbix_server [29578]: unknown parameter "serviceurl" in config file "/etc/zabbix/vmbix_module.conf", line 2

I have verified the content of vmbix_module.conf and the syntax is well formatted.

Could you help me ?

Thank you,

Jérôme

**Comment by dav3860** [comment]
Hi,
Can you put on pastebin the contents of your /etc/vmbix/vmbix.conf file and the part of /var/log/zabbix/zabbbix_server.log corresponding to a server start ?

**Comment by FireHelmet** [comment]
Hi !

Yes, of course

vmbix.conf
`# The VMWare API URL
serviceurl=MYVCENTER

# The username to use to connect to the VMWare API
username=MYUSER

# The password to use to connect to the VMWare API
password=MYPASSWORD

# The IP address vmbix will listen to
bindaddress=127.0.0.1

# The port vmbix will listen to
listenport=12050

# The pid file that the vmbix daemon will use
pidfile=/var/run/vmbix.pid

# The interval for performance metrics queries (defaults to 300s)
interval=300

# Use the VMWare UUID to identify objects (defaults to false)
useuuid=false

# The VM cache TTL (defaults to 15mn)
vmCacheTtl=5

# The hypervisor cache TTL (defaults to 15mn)
esxiCacheTtl=5

# The datastore cache TTL (defaults to 15mn)
dsCacheTtl=5

# The performance counter ID cache TTL (defaults to 15mn)
perfIdCacheTtl=5

# The performance counter cache TTL (defaults to 15mn)
counterCacheTtl=5

# The host runtime info cache TTL (defaults to 15mn)
hriCacheTtl=5

# The cluster cache TTL (defaults to 15mn)
clCacheTtl=5

# The VM cache size (defaults to 1000, recommended : vm count + n)
vmCacheSize=1000

# The hypervisor cache size (defaults to 100, recommended : esx count + n)
esxiCacheSize=100

# The datastore cache size (defaults to 100, recommended : ds count + n)
dsCacheSize=500

# The perfomance counter ID cache size (defaults to 1000)
perfIdCacheSize=1000

# The perfomance counter cache size (defaults to 1000)
counterCacheSize=1000

# The host runtime info cache size (defaults to 100, recommended : esx count + n
)
hriCacheSize=100

# The cluster cache size (defaults to 100, recommended : cl count x 2)
clCacheSize=10`

zabbix_server.log
` 29331:20160316:094755.759 Starting Zabbix Server. Zabbix 3.0.1 (revision 58734).
 29331:20160316:094755.759 ****** Enabled features ******
 29331:20160316:094755.760 SNMP monitoring:           YES
 29331:20160316:094755.760 IPMI monitoring:           YES
 29331:20160316:094755.760 Web monitoring:            YES
 29331:20160316:094755.760 VMware monitoring:         YES
 29331:20160316:094755.760 SMTP authentication:       YES
 29331:20160316:094755.760 Jabber notifications:      YES
 29331:20160316:094755.760 Ez Texting notifications:  YES
 29331:20160316:094755.760 ODBC:                      YES
 29331:20160316:094755.760 SSH2 support:              YES
 29331:20160316:094755.760 IPv6 support:              YES
 29331:20160316:094755.760 TLS support:               YES
 29331:20160316:094755.760 ******************************
 29331:20160316:094755.760 using configuration file: /etc/zabbix/zabbix_server.conf
 29331:20160316:094755.760 Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
zabbix_server [29331]: unknown parameter "serviceurl" in config file "/etc/zabbix/vmbix_module.conf", line 2`

Thank you for your quick support !

Jérôme

**Comment by dav3860** [comment]
OK I see, you confused two files :
- /etc/vmbix/vmbix.conf is the config file for VmBix.
- /etc/zabbix/vmbix_module.conf is the config file for the loadable module
Here is a sample /etc/zabbix/vmbix_module.conf :
https://github.com/dav3860/vmbix_zabbix_module/blob/master/vmbix_module.conf.sample

**Comment by FireHelmet** [comment]
Oh sorry, yes now the zabbix-server start correctly. In addition when I test zabbix_agentd -t vmbix[vm.guest.os,FRAP050], I have this message

`zabbix_agentd [1573]: Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
*** stack smashing detected ***: zabbix_agentd terminated`

Any idea ?

**Comment by dav3860** [comment]
No, it shouldn't be necessary. Did you compile the module with the sources of the exact same version of your Zabbix server ?
Can you try : zabbix_agentd -t vmbix.ping

**Comment by FireHelmet** [comment]
Yes, same version ;)

Result of your command

`zabbix_agentd [2287]: Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
vmbix.ping                                    [m|ZBX_NOTSUPPORTED] [Invalid number of key parameters]`

**Comment by dav3860** [comment]
Hum, try it with the server instead of the agent.

**Comment by FireHelmet** [comment]
Yes, but how to ? by CLI ?

**Comment by dav3860** [comment]
Like stated in the README :

/etc/zabbix/zabbix_server.conf:
```
LoadModulePath=/usr/lib/zabbix/modules
LoadModule=vmbix.so
```

And restart the server.

**Comment by FireHelmet** [comment]
Hello dav3860,

I don't have the same line, because in my zabbix appliance (used for test only, of course), "modules" is a file and not a directory.

`LoadModulePath=/usr/lib/zabbix`
`LoadModule=vmbix.so`

`root@zabbix:/home/appliance# ls /usr/lib/zabbix/modules
/usr/lib/zabbix/modules
root@zabbix:/home/appliance# cd /usr/lib/zabbix/modules
bash: cd: /usr/lib/zabbix/modules: Not a directory`

Is it normal ?

**Comment by dav3860** [comment]
I don't use the appliance. You can put the vmbix.so file wherever you want. Just update the configuration file with its location.

**Comment by FireHelmet** [comment]
Yes, so it's OK, the vmbix.so is in good location. In addition the zabbix-server process load the vmbix.so because it's indicated in log. I will try add template and test directly with a host.

I keep you informed, thank you,

**Comment by FireHelmet** [comment]
I have added a host with templates for module, in this order, VM, ESX and then vcenter. But zabbix-server crash when he try to use vmbix. In addition, it work perfectly without vmbix module and with vmbix template without module, of course. Maybe, the problem come from vmbix.so, badly compiled :(.

**Comment by dav3860** [comment]
Please try with the new RPM or DEB packages.
