### ISSUE TITLE
*** stack smashing detected  when loading , then the proxy restarts

### ISSUE THREAD

**Issue by ptempier** [dav3860/vmbix_zabbix_module#3]
*** stack smashing detected ***: /usr/sbin/zabbix_proxy: poller #31 [got 0 values in 0.000000 sec, getting values] terminated

Using 3.0.c

dN#p
i$0&j
__gmon_start__
_fini
_ITM_deregisterTMCloneTable
_ITM_registerTMCloneTable
__cxa_finalize
_Jv_RegisterClasses
CONFIG_VMBIX_PORT
zbx_module_vmbix
zbx_module_vmbix_ping
__zbx_zbx_error
exit
__zbx_zabbix_log
parse_cfg_file
__assert_fail
zbx_tcp_connect
__zbx_zbx_dsprintf
strlen
zbx_tcp_send_ext
zbx_tcp_recv_ext
strcmp
zbx_rtrim
strdup
free
zbx_tcp_close
__stack_chk_fail
zbx_module_api_version
zbx_module_item_timeout
zbx_module_item_list
zbx_module_init
time
srand
zbx_module_uninit
concat
calloc
zbx_strlcpy
libc.so.6
_edata
__bss_start
_end
GLIBC_2.4
GLIBC_2.2.5
%z" 
%r" 
%j" 
%b" 
%Z" 
%R" 
%J" 
%B" 
%:" 
=R# 
="# 
fffff.
5]! 
0s#H
0s#H
D$ H
vmbix
vmbix.ping
Timeout while executing operation
127.0.0.1
/etc/zabbix/vmbix_module.conf
Loading VmBix module configuration file %s
vmbix-3.0.c
value
ZBX_NOTSUPPORTED
VmBix Timeout: %d (s)
VmBix Host: %s
VmBix Port: %d
3.0.1
Zabbix Version: %s
Incorrect number of parameters, expecting at least one parameter.
Received reply from VmBix. Query: %s, result: %s
Invalid number of key parameters
VmBixModuleTimeout
VmBixPort
VmBixHost
get_value
;*3$"
GCC: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
.symtab
.strtab
.shstrtab
.note.gnu.build-id
.gnu.hash
.dynsym
.dynstr
.gnu.version
.gnu.version_r
.rela.dyn
.rela.plt
.init
.text
.fini
.rodata
.eh_frame_hdr
.eh_frame
.init_array
.fini_array
.jcr
.dynamic
.got
.got.plt
.data
.bss
.comment
crtstuff.c
__JCR_LIST__
deregister_tm_clones
register_tm_clones
__do_global_dtors_aux
completed.6973
__do_global_dtors_aux_fini_array_entry
frame_dummy
__frame_dummy_init_array_entry
vmbix-3.0.c
item_timeout
CONFIG_MODULE_TIMEOUT
CONFIG_VMBIX_HOST
keys
get_signal_handler
zbx_module_set_defaults
zbx_module_load_config
cfg.9454
get_value
__PRETTY_FUNCTION__.9466
__FRAME_END__
__JCR_END__
__dso_handle
_DYNAMIC
__TMC_END__
_GLOBAL_OFFSET_TABLE_
free@@GLIBC_2.2.5
_ITM_deregisterTMCloneTable
zbx_strlcpy
__zbx_zbx_error
_edata
_fini
strlen@@GLIBC_2.2.5
__stack_chk_fail@@GLIBC_2.4
__zbx_zabbix_log
__assert_fail@@GLIBC_2.2.5
concat
zbx_module_item_timeout
srand@@GLIBC_2.2.5
zbx_module_item_list
zbx_module_vmbix_ping
calloc@@GLIBC_2.2.5
zbx_tcp_recv_ext
strcmp@@GLIBC_2.2.5
zbx_tcp_send_ext
zbx_module_init
__gmon_start__
zbx_module_uninit
time@@GLIBC_2.2.5
zbx_tcp_connect
parse_cfg_file
_end
CONFIG_VMBIX_PORT
__bss_start
zbx_module_api_version
_Jv_RegisterClasses
zbx_module_vmbix
exit@@GLIBC_2.2.5
_ITM_registerTMCloneTable
zbx_rtrim
strdup@@GLIBC_2.2.5
__zbx_zbx_dsprintf
__cxa_finalize@@GLIBC_2.2.5
_init
zbx_tcp_close

**Comment by ptempier** [comment]
... that was the strings of the mbix.so module

**Comment by dav3860** [comment]
You need to configure the Zabbix sources with SSL support, eg :
```
./configure --with-openssl
```

RPM & DEB packages are now automatically created, you can use them (see README).
