### ISSUE TITLE
Vmbix3.0 module error

### ISSUE THREAD

**Issue by tieungao88** [dav3860/vmbix_zabbix_module#5]
Hi ,
I have problem: 
```
make vmbix-3.0
gcc -shared -o vmbix.so vmbix-3.0.c -I../../../include -fPIC
vmbix-3.0.c:23:20: fatal error: common.h: No such file or directory
 #include "common.h"
                    ^
compilation terminated.
make: *** [vmbix-3.0] Error 1
```
What is wrong? 

Thanks.

**Comment by dav3860** [comment]
Hi,
You can download pre-compiled packages in DEB & RPM format [here](https://bintray.com/dav3860/generic/vmbix-zabbix-module/view#files) as stated in the README.
If you wa

**Comment by tieungao88** [comment]
Thank you. I resolve this problem but when I discover Vcenter (5.5), I recived resulft = 0 for any items. Can you tel me about problem?

Thanks.

**Comment by dav3860** [comment]
Can you explain your problem precisely ?
