### ISSUE TITLE
Cannot use loadable module

### ISSUE THREAD

**Issue by Gwynnbleid1** [dav3860/vmbix_zabbix_module#6]
Hi. 
I can't use loadable module for zabbix. I tried testing it using this command:
zabbix_agentd -t vmbix[version]
zabbix_agentd [3411]: Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
vmbix[version]                                [s|ZBX_NOTSUPPORTED]

As far as i can tell module is loaded correctly. Here is agent log:
  1267:20160726:154508.695 Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
  1267:20160726:154508.695 loaded modules: vmbix.so
  1267:20160726:154508.696 agent #0 started [main process]
  1283:20160726:154508.697 agent #3 started [listener #2]
  1285:20160726:154508.698 agent #5 started [active checks #1]
  1284:20160726:154508.699 agent #4 started [listener #3]
  1281:20160726:154508.700 agent #2 started [listener #1]
  1280:20160726:154508.701 agent #1 started [collector]
  1285:20160726:154508.702 active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused)
zabbix_agentd [2357]: Is this process already running? Could not lock PID file [/var/run/zabbix/zabbix_agentd.pid]: [11] Resource temporarily unavailable

vmbix seem also fine:
zabbix_get -s 127.0.0.1 -p 12050 -k vmbix.version
2.4.0.80

I installed everything from packages.

**Comment by dav3860** [comment]
Hi,
The right method is "[vmbix.version](https://github.com/dav3860/vmbix/wiki/vmbix.version)", not "version". So you can query VmBix through the agent with : 
```
LINUXBOX ~ # zabbix_agentd -t "vmbix[vmbix.version]"
zabbix_agentd [6056]: Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
vmbix[vmbix.version]                          [s|2.5.0.89]
```

**Comment by farhandiwan** [comment]
I  was encountering this and   it solved the problem.
