### ISSUE TITLE
Zabbix 3.2

### ISSUE THREAD

**Issue by Warfunck** [dav3860/vmbix_zabbix_module#7]
I updated my zabbix from 3.0.4 to 3.2. After that vmbix stopped working:
579:20160923:110102.074 using configuration file: /etc/zabbix/zabbix_server.conf
579:20160923:110102.074 unsupported module "vmbix.so" version: 1
579:20160923:110102.074 loading modules failed, exiting... 
Is version 3.2 of zabbix server supported by vmbix.so? If not, kindly inform when the vmbix module will be updated in order to support zabbix 3.2

**Comment by dav3860** [comment]
Hi,
the VmBix loadable module was updated 12 days ago to support ZAbbix 3.2.
