### ISSUE TITLE
Can't get data from ESXi Host.

### ISSUE THREAD

**Issue by belykhk** [dav3860/vmbix_zabbix_module#9]
Hello, recently i installed VMBIX on my zabbix server (3.2.1), and i can't get data i interested in to get from ESXi host (like datasote freespace\latency). Actually i can't get any data from ESXi except name of it or CPU usage(which is broken, cause it shows 0).

VMBIX and VMBIX_Module installed from precompiled .deb packets. Templates get from vmbix repo.

zabbix_get output sample:
```
$ zabbix_get -s 127.0.0.1 -p 12050 -k about[*]
VMware ESXi 5.1.0 build-2000251
$ zabbix_get -s 127.0.0.1 -p 12050 -k vmbix[datastore.size,{HOST.HOST},free]
ZBX_NOTSUPPORTED
$ 
```

**Comment by dav3860** [comment]
Hi, you must connect to a vCenter, not an ESXi host.

**Comment by belykhk** [comment]
I think about that, but no changes.

**Comment by belykhk** [comment]
After wait (like 5 hours) data start to show. Sorry for disturbance.
